package org.scalafmt.tests

class InfixSuite extends BaseScalaPrinterTest {
  check("(a :!= b) == c")
  check("b -> (c :: d)")
  check("a + (())")
  check("a :: b :: c")
  check("(a :: b) :: c")
  check("a + b * c")
  check("a + b - c")
  check("a + (b - c) * d")
  check("a + (b - c * d)")
  check("(a + b) * c")
  check("(a + b) * c * d")
  check("(a + b) * (c * d)")
  check("(a + b) * (if (true) c else d)")
  check("b -> (c + d)")
  check("(a :: b) == c d ==(e)")
  checkCase("case (a :: b) :: c =>")
  checkCase("case (a @ A()) :: c =>")
  checkType("(A :: B) :: C")
  checkType("(A :: b.B) :: C")
  check("(a /: b) to 5")
  check("r /: (1 to 5)")
  check("a(b :: (c d e):_*)")
  check("(a := b) op c")
  check("a t_= (a b c)")
  check("(a b c) +: d")
  check("a || !b")
  check("a + b")
  check("a op[T] b")
  check("a b ((c, d))")
}
